name: Deploy Azure Resources:ClientAdvisior

on:
  push:
    branches:
      - main
    # Trigger on changes in these specific paths
    paths:
      - 'ClientAdvisor/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install Bicep CLI
        run: az bicep install
      
      - name: Check and Create Resource Group
        id: check_create_rg
        run: |
          set -e  
          echo "Checking if resource group exists..."
          rg_exists=$(az group exists --name pslautomationca)
          if [ "$rg_exists" = "false" ]; then
            echo "Resource group does not exist. Creating..."
            az group create --name pslautomationbyoa2 --location eastus || { echo "Error creating resource group"; exit 1; }
          else
            echo "Resource group already exists."
          fi
          
      - name: Deploy Bicep Template
        id: deploy
        run: |
          set -e
          az deployment group create \
            --resource-group pslautomationbyoa2 \
            --template-file ClientAdvisor/Deployment/bicep/main.bicep \
            --parameters solutionPrefix=pslca 
      
      - name: Send Notification on Failure
        if: failure()
        run: |
          curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"failureMessage\": \"$output\"}"
