name: Tests

on:
  push:
    branches: PSL-Workflow-8079
  pull_request:
    branches: PSL-Workflow-8079
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_call:
  merge_group:

jobs:
  test_client_advisor:
    name: Client Advisor Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Backend Dependencies
        run: |
          cd ClientAdvisor/App
          python -m pip install -r requirements.txt
          python -m pip install coverage pytest-cov
      - name: Run Backend Tests with Coverage
        run: |
          cd ClientAdvisor/App
          python -m pytest --cov=app --cov-report=xml --cov-report=html --junitxml=coverage-junit.xml
      - uses: actions/upload-artifact@v4
        with:
          name: client-advisor-coverage
          path: |
            ClientAdvisor/coverage.xml
            ClientAdvisor/coverage-junit.xml
            ClientAdvisor/htmlcov/
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        run: |
          cd ClientAdvisor/App/frontend
          npm install
      - name: Run Frontend Tests with Coverage
        run: |
          cd ClientAdvisor/App/frontend
          npm run test -- --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: client-advisor-frontend-coverage
          path: |
            ClientAdvisor/App/frontend/coverage/
            ClientAdvisor/App/frontend/coverage/lcov-report/

  test_research_assistant:
    name: Research Assistant Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Backend Dependencies
        run: |
          cd ResearchAssistant/App
          python -m pip install -r requirements.txt
          python -m pip install coverage pytest-cov
      - name: Run Backend Tests with Coverage
        run: |
          cd ResearchAssistant/App
          python -m pytest --cov=app --cov-report=xml --cov-report=html --junitxml=coverage-junit.xml
      - uses: actions/upload-artifact@v4
        with:
          name: research-assistant-coverage
          path: |
            ResearchAssistant/App/coverage.xml
            ResearchAssistant/App/coverage-junit.xml
            ResearchAssistant/App/htmlcov/
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        run: |
          cd ResearchAssistant/App/frontend
          npm install
      - name: Run Frontend Tests with Coverage
        run: |
          cd ResearchAssistant/App/frontend
          npm run test -- --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: research-assistant-frontend-coverage
          path: |
            ResearchAssistant/App/frontend/coverage/
            ResearchAssistant/App/frontend/coverage/lcov-report/
